from migen.build.generic_platform import *
from migen.build.xilinx import XilinxPlatform
from migen.build.xilinx.ise import XilinxISEToolchain

_io = [
        ("tp", 0, Pins("P143"), IOStandard("LVCMOS33")),
        ("tp", 1, Pins("P140"), IOStandard("LVCMOS33")),
        ("tp", 2, Pins("P138"), IOStandard("LVCMOS33")),
        ("tp", 3, Pins("P136"), IOStandard("LVCMOS33")),
        ("tp", 4, Pins("P134"), IOStandard("LVCMOS33")),

        ("ifc_mode", 0,
            Pins("P104 P105 P110 P111"),
            IOStandard("LVCMOS33"),
            Misc("PULLUP")),

        ("clk", 0,
            Subsignal("div", Pins("P11")),
            Subsignal("in_sel", Pins("P12")),
            IOStandard("LVCMOS33")),

        ("att", 0,
            Subsignal("clk", Pins("P95")),
            Subsignal("le", Pins("P94")),
            Subsignal("rst_n", Pins("P96")),
            Subsignal("s_in", Pins("P133")),
            Subsignal("s_out", Pins("P97")),
            IOStandard("LVCMOS33")),

        ("dds_common", 0,
            Subsignal("master_reset", Pins("P102")),
            Subsignal("reset", Pins("P120")),
            Subsignal("io_reset", Pins("P129")),
            Subsignal("profile", Pins("P130 P131 P132")),
            IOStandard("LVCMOS33")),

        ("dds_sync", 0,
            Subsignal("clk0", Pins("P38"), Misc("PULLUP")),  # DDS_SYNC_CLK0
            Subsignal("clk_out_en", Pins("P86")),  # DDS_SYNC_CLK_OUTEN
            Subsignal("sync_sel", Pins("P60")),  # DDS_SYNC_CLKSEL
            Subsignal("sync_out_en", Pins("P92")),  # DDS_SYNC_OUTEN
            IOStandard("LVCMOS33")),

        ("dds", 0,
            Subsignal("rf_sw", Pins("P103")),
            Subsignal("led", Pins("P128 P126")),
            Subsignal("smp_err", Pins("P19"), Misc("PULLUP")),
            Subsignal("pll_lock", Pins("P21"), Misc("PULLUP")),
            Subsignal("io_update", Pins("P4")),
            Subsignal("sck", Pins("P3")),
            Subsignal("sdo", Pins("P113")),
            Subsignal("sdi", Pins("P2")),
            Subsignal("cs_n", Pins("P119")),
            IOStandard("LVCMOS33")),

        ("dds", 1,
            Subsignal("rf_sw", Pins("P101")),
            Subsignal("led", Pins("P118 P125")),
            Subsignal("smp_err", Pins("P28"), Misc("PULLUP")),
            Subsignal("pll_lock", Pins("P35"), Misc("PULLUP")),
            Subsignal("io_update", Pins("P10")),
            Subsignal("sck", Pins("P9")),
            Subsignal("sdo", Pins("P6")),
            Subsignal("sdi", Pins("P7")),
            Subsignal("cs_n", Pins("P5")),
            IOStandard("LVCMOS33")),

        ("dds", 2,
            Subsignal("rf_sw", Pins("P100")),
            Subsignal("led", Pins("P116 P117")),
            Subsignal("smp_err", Pins("P40"), Misc("PULLUP")),
            Subsignal("pll_lock", Pins("P41"), Misc("PULLUP")),
            Subsignal("io_update", Pins("P14")),
            Subsignal("sck", Pins("P13")),
            Subsignal("sdo", Pins("P17")),
            Subsignal("sdi", Pins("P15")),
            Subsignal("cs_n", Pins("P16")),
            IOStandard("LVCMOS33")),

        ("dds", 3,
            Subsignal("rf_sw", Pins("P98")),
            Subsignal("led", Pins("P121 P124")),
            Subsignal("smp_err", Pins("P39"), Misc("PULLUP")),
            Subsignal("pll_lock", Pins("P49"), Misc("PULLUP")),
            Subsignal("io_update", Pins("P25")),
            Subsignal("sck", Pins("P22")),
            Subsignal("sdo", Pins("P23")),
            Subsignal("sdi", Pins("P26")),
            Subsignal("cs_n", Pins("P24")),
            IOStandard("LVCMOS33")),

        ("eem", 0,
            Subsignal("io", Pins("P30")),
            Subsignal("oe", Pins("P58")),
            IOStandard("LVCMOS33")),
        ("eem", 1,
            Subsignal("io", Pins("P53")),
            Subsignal("oe", Pins("P52")),
            IOStandard("LVCMOS33")),
        ("eem", 2,
            Subsignal("io", Pins("P45")),
            Subsignal("oe", Pins("P57")),
            IOStandard("LVCMOS33")),
        ("eem", 3,
            Subsignal("io", Pins("P50")),
            Subsignal("oe", Pins("P61")),
            IOStandard("LVCMOS33")),
        ("eem", 4,
            Subsignal("io", Pins("P43")),
            Subsignal("oe", Pins("P64")),
            IOStandard("LVCMOS33")),
        ("eem", 5,
            Subsignal("io", Pins("P51")),
            Subsignal("oe", Pins("P59")),
            IOStandard("LVCMOS33")),
        ("eem", 6,
            Subsignal("io", Pins("P54")),
            Subsignal("oe", Pins("P68")),
            IOStandard("LVCMOS33")),
        ("eem", 7,
            Subsignal("io", Pins("P56")),
            Subsignal("oe", Pins("P69")),
            IOStandard("LVCMOS33")),
        ("eem", 8,
            Subsignal("io", Pins("P32")),
            Subsignal("oe", Pins("P80")),
            IOStandard("LVCMOS33")),
        ("eem", 9,
            Subsignal("io", Pins("P71")),
            Subsignal("oe", Pins("P85")),
            IOStandard("LVCMOS33")),
        ("eem", 10,
            Subsignal("io", Pins("P74")),
            Subsignal("oe", Pins("P82")),
            IOStandard("LVCMOS33")),
        ("eem", 11,
            Subsignal("io", Pins("P78")),
            Subsignal("oe", Pins("P77")),
            IOStandard("LVCMOS33")),
        ("eem", 12,
            Subsignal("io", Pins("P70")),
            Subsignal("oe", Pins("P79")),
            IOStandard("LVCMOS33")),
        ("eem", 13,
            Subsignal("io", Pins("P87")),
            Subsignal("oe", Pins("P81")),
            IOStandard("LVCMOS33")),
        ("eem", 14,
            Subsignal("io", Pins("P76")),
            Subsignal("oe", Pins("P91")),
            IOStandard("LVCMOS33")),
        ("eem", 15,
            Subsignal("io", Pins("P88")),
            Subsignal("oe", Pins("P83")),
            IOStandard("LVCMOS33")),
]


class Platform(XilinxPlatform):
    def __init__(self):
        XilinxPlatform.__init__(self, "xc2c128-6-tq144", _io)
        self.toolchain.xst_opt = "-ifmt MIXED"
        self.toolchain.par_opt = "-optimize speed"
